

[test_suite.test_check]
pass = true

[test_suite.test_assert]
pass = true

[test_suite.test_assert_uint_eq]
pass = true

[test_suite.test_assert_int_eq]
pass = true

[test_suite.test_mu_assert_double_close]
pass = true

[test_suite.test_check_fail]
pass = false
fail = "mu_check at minunit_example.c:21"
reason = "Test failed"

[test_suite.test_assert_fail]
pass = false
fail = "mu_assert at minunit_example.c:29"
reason = "foo should be <> 7"

[test_suite.test_assert_uint_eq_fail]
pass = false
fail = "mu_assert_uint_eq at minunit_example.c:37"
reason = "4 expected but was 4"

[test_suite.test_assert_int_eq_fail]
pass = false
fail = "mu_assert_int_eq at minunit_example.c:45"
reason = "1 expected but was 7"

[test_suite.test_mu_assert_double_close_fail]
pass = false
fail = "mu_assert_double_close at minunit_example.c:54"
reason = "Difference of 0.0197 not within 0.01, 4.32 !~= 4.3003"

[test_suite.test_fail]
pass = false
fail = "mu_fail at minunit_example.c:58"
reason = "Fail now!"

[test_suite.test_confirm]
prompt = "Everything ok?"
# 'y' for yes, 'n' for no:

pass = false
fail = "mu_confirm at minunit_example.c:62"
reason = "Everything ok?"


[report]
tests = 12
assertions = 12
failures = 7
